public void testMergeAfterRemove() throws Exception {
    Workload load = new Workload();
    load.name = "Cleaning";
    load.load = 10;
    EntityManager em = factory.createEntityManager();
    em.getTransaction().begin();
    load = em.merge(load);
    em.flush();
    em.getTransaction().commit();
    em.close();
    em = factory.createEntityManager();
    em.getTransaction().begin();
    load = em.find(Workload.class, load.id);
    em.remove(load);
    em.flush();
    em.getTransaction().commit();
    em.close();
    em = factory.createEntityManager();
    em.getTransaction().begin();
    em.merge(load);
    em.flush();
    em.getTransaction().commit();
    em.close();
}
