@Test
public void test() throws Exception {
    Provider provider = new Provider(Arrays.asList("1", "2", "3"), Arrays.asList("4", "5", "6"));
    // train and test files
    provider.getTrainReader();
    Assert.assertEquals(Arrays.asList("1", "2", "3"), provider.currentNames);
    provider.getTestReader();
    Assert.assertEquals(Arrays.asList("4", "5", "6"), provider.currentNames);
    // cross validation files
    provider.setNumberOfFolds(3);
    provider.getTestReader(0);
    Assert.assertEquals(Arrays.asList("1"), provider.currentNames);
    provider.getTrainReader(0);
    Assert.assertEquals(Arrays.asList("2", "3"), provider.currentNames);
    provider.getTestReader(1);
    Assert.assertEquals(Arrays.asList("2"), provider.currentNames);
    provider.getTrainReader(1);
    Assert.assertEquals(Arrays.asList("1", "3"), provider.currentNames);
    provider.getTestReader(2);
    Assert.assertEquals(Arrays.asList("3"), provider.currentNames);
    provider.getTrainReader(2);
    Assert.assertEquals(Arrays.asList("1", "2"), provider.currentNames);
    // all files
    provider.getReader();
    Assert.assertEquals(Arrays.asList("1", "2", "3", "4", "5", "6"), provider.currentNames);
}
