@Test(timeout = DEFAULT_TEST_TIMEOUT)
public void testRunNow_ChildDiamond_StopOnError_2And3Fail() throws InterruptedException {
    String group = "diamondTest";
    Task task1 = new Task("task1", group, BEAN_WAIT_JOB, true, true, "3000", "");
    taskManager.save(task1);
    // set tasks 2 and 3 to fail
    Task task2 = new Task("task2", group, "failJob", true, true, "true", "");
    taskManager.save(task2);
    Task task3 = new Task("task3", group, "failJob", true, true, "true", "");
    taskManager.save(task3);
    Task task4 = new Task("task4", group, BEAN_WAIT_JOB, true, true, "1000", "");
    taskManager.save(task4);
    // now create our task "diamond"
    task1.addChildTask(task2);
    task1.addChildTask(task3);
    taskManager.save(task1);
    task2.addChildTask(task4);
    taskManager.save(task2);
    task3.addChildTask(task4);
    taskManager.save(task3);
    schedulerManager.runTaskNow(task1);
    waitForTask(task2);
    waitForTask(task3);
    assertEquals(0, taskRunManager.findByTaskId(100).size());
}
