public void testExecute() throws Exception {
    User user = new User("self-registered");
    user.setPassword("Password1");
    user.setConfirmPassword("Password1");
    user.setFirstName("First");
    user.setLastName("Last");
    Address address = new Address();
    address.setCity("Denver");
    address.setProvince("CO");
    address.setCountry("USA");
    address.setPostalCode("80210");
    user.setAddress(address);
    user.setEmail("self-registered@raibledesigns.com");
    user.setWebsite("http://raibledesigns.com");
    user.setPasswordHint("Password is one with you.");
    bean.setUser(user);
    // start SMTP Server
    Wiser wiser = new Wiser();
    wiser.setPort(getSmtpPort());
    wiser.start();
    assertEquals("mainMenu", bean.save());
    assertFalse(bean.hasErrors());
    // verify an account information e-mail was sent
    wiser.stop();
    assertTrue(wiser.getMessages().size() == 1);
    // verify that success messages are in the session
    assertNotNull(bean.getSession().getAttribute(Constants.REGISTERED));
    SecurityContextHolder.getContext().setAuthentication(null);
}
