public void testAddAndRemoveUser() throws Exception {
    User user = new User("testuser");
    user.setPassword("testpass");
    user.setFirstName("Test");
    user.setLastName("Last");
    Address address = new Address();
    address.setCity("Denver");
    address.setCountyId("051");
    address.setStateId("OR");
    address.setCountry("US");
    address.setPostalCode("80210");
    user.setAddress(address);
    user.setEmail("testuser@appfuse.org");
    user.setWebsite("http://raibledesigns.com");
    Role role = rdao.getRoleByName(Constants.USER_ROLE);
    assertNotNull(role.getId());
    user.addRole(role);
    user = dao.saveUser(user);
    flush();
    assertNotNull(user.getId());
    user = dao.get(user.getId());
    assertEquals("testpass", user.getPassword());
    dao.remove(user.getId());
    flush();
    try {
        dao.get(user.getId());
        fail("getUser didn't throw DataAccessException");
    } catch (DataAccessException d) {
        assertNotNull(d);
    }
}
