public void testWithFail(Instances data) throws Exception {
    if (!test(data)) {
        throw m_FailReason;
    }
}
